//
// Created by apenchev on 5/13/2022.
//

#ifndef LIBRARITY_BUT_DUMBER_LIBRARYERRORCODE_H
#define LIBRARITY_BUT_DUMBER_LIBRARYERRORCODE_H

enum LibraryErrorCode {
    INVALID_OLD_PASSWORD,
    MISMATCHING_PASSWORDS,
    INVALID_READING_MODE
};

#endif //LIBRARITY_BUT_DUMBER_LIBRARYERRORCODE_H
