//
// Created by apenchev on 5/12/2022.
//

#ifndef LIBRARITY_BUT_DUMBER_WRITINGMODE_H
#define LIBRARITY_BUT_DUMBER_WRITINGMODE_H

enum WritingMode {
    NONE,
    STANDARD_IN,
    FROM_FILE
};

#endif //LIBRARITY_BUT_DUMBER_WRITINGMODE_H
