//
// Created by apenchev on 5/9/2022.
//

#ifndef LIBRARITY_BUT_DUMBER_READINGMODE_H
#define LIBRARITY_BUT_DUMBER_READINGMODE_H


enum ReadingMode {
    WHOLE_BOOK,
    PAGES,
    SENTENCES
};


#endif //LIBRARITY_BUT_DUMBER_READINGMODE_H
