//
// Created by apenchev on 5/14/2022.
//

#ifndef LIBRARITY_BUT_DUMBER_SORTINGMODE_H
#define LIBRARITY_BUT_DUMBER_SORTINGMODE_H


enum SortingMode {
    SORT_BY_NAME,
    SORT_BY_AUTHOR,
    SORT_BY_RATING
};


#endif //LIBRARITY_BUT_DUMBER_SORTINGMODE_H
