//
// Created by apenchev on 5/13/2022.
//

#ifndef LIBRARITY_BUT_DUMBER_LIBRARYERRORCODE_H
#define LIBRARITY_BUT_DUMBER_LIBRARYERRORCODE_H

enum LibraryErrorCode {
    DUPLICATE_ISBN,
    DUPLICATE_USERNAME,
    INVALID_OLD_PASSWORD,
    MISMATCHING_PASSWORDS_ERR,
    BOOK_NOT_FOUNT_ERR
};

#endif //LIBRARITY_BUT_DUMBER_LIBRARYERRORCODE_H
